key requests require url-encoding. Also fix for SearchRequest
wseemann/Roku-ECP-Wrapper-Kotlin pull request #2
Opened 2024-12-31 23:49 UTC by pupitetris

url-encode the key parameter as it is going to be part of the request URL, which is particularly important for the Lit_ case (for example, when trying to send a Space).

All url-encoding calls, including that found in SearchRequest changed to use StandardCharsets.UTF_8.name() or otherwise a MethodNotFound exception was generated at runtime (maybe only on my development Android device, but this is more compatible in general). Also, UnsupportedEncodingException has to be handled, so we just omit the encoding part inside the catch, expecting this exception to never happen as UTF_8 should always be available for URL encoding.

2025-01-03 07:58 UTC, wseemannroku commented on src/main/java/com/wseemann/ecp/request/KeyPressRequest.java
> +		} catch (UnsupportedEncodingException e) {
Can you annotate this constructor as throwing `UnsupportedEncodingException` and let the person implementing the call handle the exception? With this approach the exception is swallowed and it's probably important for the developer to know that we are attempting to encode the key they are passing.

2025-01-03 08:09 UTC, wseemann requested changes

2025-01-03 08:09 UTC, wseemann commented on src/main/java/com/wseemann/ecp/request/KeyPressRequest.java
> +		try {
Can you annotate this constructor as throwing UnsupportedEncodingException and remove the try/catch so the person implementing the call handle the exception? With this approach the exception is swallowed and it's probably important for the developer to know that we are attempting to encode the key they are passing.

2025-01-03 22:10 UTC, pupitetris commented on src/main/java/com/wseemann/ecp/request/KeyPressRequest.java
> +		try {
OK, I updated the constructors so that they let the exception through.

I also patched RoMote in this PR: https://github.com/wseemann/RoMote/pull/47

2025-01-08 06:00 UTC, wseemann approved these changes

2025-01-08 06:01 UTC, merged